//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agence
    {
        public string Code { get; set; }
        public string Libelle_Fr { get; set; }
        public string Libelle_Ar { get; set; }
        public string Adresse_Fr { get; set; }
        public string Adresse_Ar { get; set; }
        public string Ville_Fr { get; set; }
        public string Ville_Ar { get; set; }
        public string N_Teleph { get; set; }
        public string N_Cpt_CCP { get; set; }
        public string N_Cpt_Bnq { get; set; }
        public string N_Cpt_Trs { get; set; }
        public string Code_Postal { get; set; }
        public string Code_CP { get; set; }
        public string Code_CI { get; set; }
        public Nullable<byte> Delai_MR_Mois { get; set; }
        public Nullable<byte> Delai_MR_Jour { get; set; }
        public Nullable<byte> Delai_PR_Mois { get; set; }
        public Nullable<byte> Delai_PR_Jour { get; set; }
        public Nullable<byte> Delai_TO_Mois { get; set; }
        public Nullable<byte> Delai_TO_Jour { get; set; }
        public Nullable<byte> Delai_Ctx_Mois { get; set; }
        public Nullable<byte> Delai_Ctx_Jour { get; set; }
        public Nullable<float> Taux_MR_PR { get; set; }
        public Nullable<float> Taux_MR_Sup { get; set; }
        public Nullable<float> Taux_PR_PR { get; set; }
        public Nullable<float> Taux_PR_Sup { get; set; }
        public string C_Banque { get; set; }
        public string C_Ag_Banque { get; set; }
        public string Centre_CCP { get; set; }
        public Nullable<int> Seuil_Maj { get; set; }
        public string Id_Agence { get; set; }
    }
}
