//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agence_Banq
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agence_Banq()
        {
            this.Bordereaux = new HashSet<Bordereau>();
            this.Cotisant_Account = new HashSet<Cotisant_Account>();
            this.Cotisants = new HashSet<Cotisant>();
            this.Encaisses = new HashSet<Encaiss>();
            this.Opposition_Detail = new HashSet<Opposition_Detail>();
        }
    
        public string Code { get; set; }
        public string Libelle { get; set; }
        public string Libelle_Ar { get; set; }
        public bool Place { get; set; }
        public string Code_Banque { get; set; }
        public string Agence_Existe { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Banque Banque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bordereau> Bordereaux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotisant_Account> Cotisant_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotisant> Cotisants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encaiss> Encaisses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opposition_Detail> Opposition_Detail { get; set; }
    }
}
