//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annee_CP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Annee_CP()
        {
            this.DAS = new HashSet<DA>();
            this.Decomptes = new HashSet<Decompte>();
            this.Ligne_DAS = new HashSet<Ligne_DAS>();
            this.Ligne_DAS_Info = new HashSet<Ligne_DAS_Info>();
            this.Ligne_DAS_Info_Archive = new HashSet<Ligne_DAS_Info_Archive>();
            this.Ligne_DAS_Info_Err_Ok = new HashSet<Ligne_DAS_Info_Err_Ok>();
            this.Ligne_DAS_Info_Err_Rejet = new HashSet<Ligne_DAS_Info_Err_Rejet>();
            this.Mandats = new HashSet<Mandat>();
            this.Sessions = new HashSet<Session>();
        }
    
        public string Annee { get; set; }
        public string Etat { get; set; }
        public string Code_Usager { get; set; }
        public string Id_Agence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DA> DAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Decompte> Decomptes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligne_DAS> Ligne_DAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligne_DAS_Info> Ligne_DAS_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligne_DAS_Info_Archive> Ligne_DAS_Info_Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligne_DAS_Info_Err_Ok> Ligne_DAS_Info_Err_Ok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligne_DAS_Info_Err_Rejet> Ligne_DAS_Info_Err_Rejet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mandat> Mandats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
