//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bomop
    {
        public int id_bomop { get; set; }
        public string maitre_ouvrage { get; set; }
        public string rais_soc { get; set; }
        public string adresse_projet { get; set; }
        public string ville { get; set; }
        public string commune { get; set; }
        public string delai_projet { get; set; }
        public Nullable<int> montant_projet { get; set; }
        public Nullable<int> numero_pomp { get; set; }
        public string cibler_par { get; set; }
        public Nullable<System.DateTime> cilbler_le { get; set; }
        public Nullable<System.DateTime> date_controle { get; set; }
        public string controleur { get; set; }
        public string obs { get; set; }
        public string utilisateur { get; set; }
        public string id_agence { get; set; }
    }
}
