//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bordereau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bordereau()
        {
            this.Encaisses = new HashSet<Encaiss>();
        }
    
        public int IdBord { get; set; }
        public int Num_Int { get; set; }
        public System.DateTime Date_Bord { get; set; }
        public string Code_Banque { get; set; }
        public string C_Ag_Ban { get; set; }
        public string Etat { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Agence_Banq Agence_Banq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encaiss> Encaisses { get; set; }
    }
}
