//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bordereau_Rmp
    {
        public int Id_Bord { get; set; }
        public System.DateTime Date_Bord { get; set; }
        public decimal Montant { get; set; }
        public int Nbr_Lignes { get; set; }
        public string Type { get; set; }
        public string Etat { get; set; }
        public string Id_Agence { get; set; }
    }
}
