//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cert_Bleu_Temp
    {
        public string N_Annee { get; set; }
        public string N_Employeur { get; set; }
        public string N_Salarie { get; set; }
        public string N_CB { get; set; }
        public decimal Salaire { get; set; }
        public int Nb_Jour { get; set; }
        public string Profession { get; set; }
        public bool Assuj_CI { get; set; }
        public string Sit_Fam { get; set; }
        public string Type_Nb_Jour { get; set; }
        public string Code_User { get; set; }
        public string Id_Agence { get; set; }
    }
}
