//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chantier_CI
    {
        public string N_Emp_CI { get; set; }
        public int N_Chantier { get; set; }
        public System.DateTime Date_A_Ch { get; set; }
        public string Add_Chantier { get; set; }
        public System.DateTime Date_R_Ch { get; set; }
        public string Valide { get; set; }
        public int Nb_Salarie { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date_V { get; set; }
        public string Etat { get; set; }
        public Nullable<System.DateTime> Date_Paiement { get; set; }
        public string Id_Agence { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Reception_CI Reception_CI { get; set; }
    }
}
