//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conge_Annuel
    {
        public string N_Annee { get; set; }
        public string N_Salarie { get; set; }
        public bool Assuj_CI { get; set; }
        public decimal Dette { get; set; }
        public decimal Brut { get; set; }
        public decimal Sec_Soc { get; set; }
        public decimal IRG { get; set; }
        public decimal Net { get; set; }
        public Nullable<float> N_Jours_Conge { get; set; }
        public Nullable<decimal> Cot_CI { get; set; }
        public string Code_Saisie { get; set; }
        public string Dette_Neant { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Salarie Salarie { get; set; }
    }
}
