//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrainte
    {
        public int N_Piece { get; set; }
        public string N_Cotisant { get; set; }
        public System.DateTime D_Etab { get; set; }
        public decimal Mt_P { get; set; }
        public decimal Mt_A { get; set; }
        public decimal Mt_F { get; set; }
        public string Per_Debut { get; set; }
        public string Per_Fin { get; set; }
        public string Etat { get; set; }
        public string Observ { get; set; }
        public int Num_Aver { get; set; }
        public string Code_User { get; set; }
        public string Cours { get; set; }
        public string Trib { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Cotisant Cotisant { get; set; }
    }
}
