//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConvocationPieceHistorique
    {
        public int Id { get; set; }
        public string N_cotisant { get; set; }
        public string Id_agence { get; set; }
        public System.DateTime Date_convocation { get; set; }
        public Nullable<System.DateTime> Date_recepetion { get; set; }
        public string NomAgence { get; set; }
        public string TelephoneAgence { get; set; }
        public string FaxAgence { get; set; }
        public string NomPrenomEmployeur { get; set; }
        public string AdresseCH { get; set; }
        public string AdresseAgence { get; set; }
        public string NomPrenomControleur { get; set; }
        public Nullable<bool> Livres_legaux { get; set; }
        public string BilanComptablesAnnees { get; set; }
        public Nullable<bool> Factures_SousTraitance { get; set; }
        public Nullable<bool> RC_CF_chequebarre_attesAffCNAS_EN { get; set; }
        public Nullable<bool> ContratsMarches_Convetions_ODS { get; set; }
        public string DeclarationCNASAnnees { get; set; }
        public string Autres { get; set; }
        public Nullable<int> Id_cotisantnonaff { get; set; }
    }
}
