//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotisant_History
    {
        public int Id { get; set; }
        public string Numero { get; set; }
        public string Rais_Soc_Fr { get; set; }
        public string Nom_Comm_Fr { get; set; }
        public string Adresse_Fr { get; set; }
        public string Ville_Fr { get; set; }
        public string N_Reg_Comm { get; set; }
        public Nullable<System.DateTime> D_Delivre { get; set; }
        public string N_Fiscal { get; set; }
        public Nullable<System.DateTime> D_Depot_Dos { get; set; }
        public Nullable<System.DateTime> D_Debut_Act { get; set; }
        public Nullable<System.DateTime> D_Recrut { get; set; }
        public Nullable<int> Effect_P { get; set; }
        public Nullable<bool> Exonere_MR { get; set; }
        public Nullable<bool> Exonere_PR { get; set; }
        public string Classe { get; set; }
        public string C_Statut { get; set; }
        public string C_Nap { get; set; }
        public string C_Nation { get; set; }
        public Nullable<System.DateTime> D_Creat { get; set; }
        public string Code_User { get; set; }
        public string Num_Caco { get; set; }
        public string Wil_Chantier { get; set; }
        public Nullable<short> Wil_Seq { get; set; }
        public Nullable<byte> Type { get; set; }
        public string TP { get; set; }
        public string Hyd { get; set; }
        public Nullable<short> Wil_Deliv_Reg { get; set; }
        public string B { get; set; }
        public Nullable<System.DateTime> Date_Op { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Cotisant Cotisant { get; set; }
    }
}
