//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotisantNonAff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CotisantNonAff()
        {
            this.Chantiers = new HashSet<Chantier>();
        }
    
        public string Id_Agence { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public string Rais_Soc_fr { get; set; }
        public string Nom_comm_fr { get; set; }
        public string AdresseFr { get; set; }
        public string VilleFr { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string N_Teleph { get; set; }
        public string NumeroProvisoire { get; set; }
        public string N_Fax { get; set; }
        public string N_Fiscal { get; set; }
        public Nullable<System.DateTime> D_Debut_Act { get; set; }
        public string Position { get; set; }
        public string Etat { get; set; }
        public string Type { get; set; }
        public string Rais_Soc_Ar { get; set; }
        public string Nom_Comm_Ar { get; set; }
        public string AdresseAr { get; set; }
        public string NouveauNumeroCotisant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chantier> Chantiers { get; set; }
    }
}
