//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotisant_Account
    {
        public string Numero { get; set; }
        public string N_Cpt { get; set; }
        public string C_Banque { get; set; }
        public string C_Ag_Banq { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Agence_Banq Agence_Banq { get; set; }
        public virtual Cotisant Cotisant { get; set; }
    }
}
