//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DA
    {
        public string N_Annee { get; set; }
        public string N_Employeur { get; set; }
        public int Num_DAS { get; set; }
        public decimal Mt_Total { get; set; }
        public string Code_User { get; set; }
        public Nullable<int> Sal_Total { get; set; }
        public Nullable<System.DateTime> D_Recep { get; set; }
        public string Id_Agence { get; set; }
        public string Type { get; set; }
        public string ModePaie { get; set; }
    
        public virtual Annee_CP Annee_CP { get; set; }
    }
}
