//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decompte
    {
        public int Numero { get; set; }
        public string N_Annee { get; set; }
        public string N_Salarie { get; set; }
        public System.DateTime Date_Dec { get; set; }
        public System.DateTime C_Session { get; set; }
        public string Mode_Paie { get; set; }
        public string Type_Paie { get; set; }
        public string N_Employeur { get; set; }
        public bool Assuj_CI { get; set; }
        public string Sit_Fam { get; set; }
        public decimal Net { get; set; }
        public decimal IRG { get; set; }
        public decimal SS { get; set; }
        public decimal CI { get; set; }
        public string Etat { get; set; }
        public string Banque { get; set; }
        public string Ag_Banque { get; set; }
        public string N_Compte { get; set; }
        public string Observ { get; set; }
        public string Code_Saisie { get; set; }
        public Nullable<decimal> Brut { get; set; }
        public string Code_Valide { get; set; }
        public string Nature { get; set; }
        public Nullable<float> Nb_Jours_Conge { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Annee_CP Annee_CP { get; set; }
        public virtual Salarie Salarie { get; set; }
        public virtual Session Session { get; set; }
    }
}
