//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decompte_CI
    {
        public int Ord { get; set; }
        public string N_Salarie { get; set; }
        public string N_Emp_CI { get; set; }
        public int N_Chatier { get; set; }
        public string Nom_Sal { get; set; }
        public string Prenom_Sal { get; set; }
        public string Fonctin { get; set; }
        public System.DateTime D_Recrutement { get; set; }
        public double Nb_H_Ind { get; set; }
        public double Salaire_H { get; set; }
        public Nullable<double> Salaire_Brut { get; set; }
        public System.DateTime Date_D { get; set; }
        public string Valide { get; set; }
        public string Code { get; set; }
        public Nullable<double> Salaire_Dec { get; set; }
        public string Rq { get; set; }
        public Nullable<double> Nb_H_Ind_R { get; set; }
        public System.DateTime Date_R { get; set; }
        public Nullable<double> Nb_Heur_Travail { get; set; }
        public string Flag { get; set; }
        public Nullable<int> Annee { get; set; }
        public string Id_Agence { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Date_Naiss { get; set; }
    
        public virtual Reception_CI Reception_CI { get; set; }
    }
}
