//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ecrit_Enc
    {
        public int Id_Ecrit { get; set; }
        public int Enc_Genere { get; set; }
        public int N_Encaiss { get; set; }
        public int N_DAC { get; set; }
        public string C_Operation { get; set; }
        public System.DateTime Date_Encaiss { get; set; }
        public string Canal { get; set; }
        public string C_Nature { get; set; }
        public string N_Cotisant { get; set; }
        public string C_Periode { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public string Observ { get; set; }
        public string Etat { get; set; }
        public string Code_Usager { get; set; }
        public Nullable<System.DateTime> Date_Fact { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Canal Canal1 { get; set; }
        public virtual Cotisant Cotisant { get; set; }
        public virtual Nature Nature { get; set; }
        public virtual Periode Periode { get; set; }
    }
}
