//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeur_CI
    {
        public string N_Emp_CI { get; set; }
        public string Nom_Emp_CI { get; set; }
        public string Prenom_Emp_CI { get; set; }
        public string Nom_Com { get; set; }
        public string Code { get; set; }
        public string Id_Agence { get; set; }
    }
}
