//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeur
    {
        public string Numero { get; set; }
        public string Rais_Soc { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string C_Postal { get; set; }
        public bool Position { get; set; }
        public string NCpt_CCP { get; set; }
        public string NCpt_Banque { get; set; }
        public string Ag_Banque { get; set; }
        public string Banque { get; set; }
        public string Rais_Soc_Latin { get; set; }
        public string Id_Agence { get; set; }
    }
}
