//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encaiss
    {
        public int Id { get; set; }
        public string N_Cheque { get; set; }
        public Nullable<System.DateTime> D_Emission { get; set; }
        public System.DateTime D_Recep { get; set; }
        public string Etat { get; set; }
        public string Type { get; set; }
        public int N_Encaiss { get; set; }
        public int N_Bord { get; set; }
        public string N_Cotisant { get; set; }
        public string Periode { get; set; }
        public string C_Canal { get; set; }
        public decimal Montant { get; set; }
        public string Code_Banque { get; set; }
        public string Ag_Banq { get; set; }
        public string Observ { get; set; }
        public string Code_Usager { get; set; }
        public string Id_Agence { get; set; }
        public string Normalise { get; set; }
    
        public virtual Agence_Banq Agence_Banq { get; set; }
        public virtual Bordereau Bordereau { get; set; }
        public virtual Canal Canal { get; set; }
        public virtual Cotisant Cotisant { get; set; }
        public virtual Periode Periode1 { get; set; }
    }
}
