//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncaissWeb
    {
        public int Id { get; set; }
        public string NumPiece { get; set; }
        public System.DateTime D_Piece { get; set; }
        public System.DateTime D_Recep { get; set; }
        public Nullable<System.DateTime> D_Identif { get; set; }
        public string Etat { get; set; }
        public string N_Cotisant { get; set; }
        public string Observation { get; set; }
        public decimal Montant { get; set; }
        public string Code_User { get; set; }
        public string Id_Agence { get; set; }
    }
}
