//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntetPlanCharge
    {
        public System.DateTime DateDebut { get; set; }
        public Nullable<int> NumOrdre { get; set; }
        public System.DateTime DateFin { get; set; }
        public string CodeUser { get; set; }
        public string Id_Agence { get; set; }
        public string TypeControle { get; set; }
    }
}
