//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntrepriseNonAff
    {
        public string Id_Agence { get; set; }
        public string Rais_Soc_Fr { get; set; }
        public string Nom_Comm_Fr { get; set; }
        public string Adresse_Fr { get; set; }
        public string Rais_Soc_Ar { get; set; }
        public string Nom_Comm_Ar { get; set; }
        public string Adresse_Ar { get; set; }
        public string N_Teleph { get; set; }
        public string N_Fax { get; set; }
        public string N_Fiscal { get; set; }
        public System.DateTime D_Debut_Act { get; set; }
        public string Wilaya { get; set; }
        public string CodeUser { get; set; }
        public string Position { get; set; }
        public string Sous_Control { get; set; }
        public string Sous_Content { get; set; }
        public string Sous_Exploit { get; set; }
        public string Etat { get; set; }
    }
}
