//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTREPRISE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTREPRISE()
        {
            this.ConvocationPieces = new HashSet<ConvocationPiece>();
            this.FicheControlePs = new HashSet<FicheControleP>();
            this.PvInfractionPieces = new HashSet<PvInfractionPiece>();
            this.RapportVisitePieceRAS = new HashSet<RapportVisitePieceRA>();
        }
    
        public string Id_Agence { get; set; }
        public string Numero { get; set; }
        public int Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConvocationPiece> ConvocationPieces { get; set; }
        public virtual Cotisant Cotisant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FicheControleP> FicheControlePs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PvInfractionPiece> PvInfractionPieces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RapportVisitePieceRA> RapportVisitePieceRAS { get; set; }
    }
}
