//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hist_Das
    {
        public int Id { get; set; }
        public string N_Employeur { get; set; }
        public string N_Annee { get; set; }
        public decimal Anc_Ass { get; set; }
        public decimal Nouv_Ass { get; set; }
        public System.DateTime Date_DAS { get; set; }
        public string Code_User { get; set; }
        public string Id_Agence { get; set; }
    }
}
