//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistModifAffilSal
    {
        public int Id { get; set; }
        public string NomOld { get; set; }
        public string PrenomOld { get; set; }
        public string NomNew { get; set; }
        public string PrenomNew { get; set; }
        public System.DateTime DateModif { get; set; }
        public string C_User { get; set; }
        public string Id_Agence { get; set; }
    }
}
