//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identification
    {
        public string N_Cotisant { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<System.DateTime> Date_Nais { get; set; }
        public string Lieu_Nais { get; set; }
        public string Adresse { get; set; }
        public string Prenom_Pere { get; set; }
        public string Nom_Mere { get; set; }
        public string Prenom_Mere { get; set; }
        public string Code_User { get; set; }
        public string Id_Agence { get; set; }
    }
}
