//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jours_Feries
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date_Feries { get; set; }
        public string Event { get; set; }
        public string Code { get; set; }
        public string Id_Agence { get; set; }
    }
}
