//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligne_DAS
    {
        public int N_Ordre { get; set; }
        public string Annee_DAS { get; set; }
        public string Empl_DAS { get; set; }
        public string Salarie_DAS { get; set; }
        public string Profession { get; set; }
        public decimal Sal_Annuel { get; set; }
        public int Nbj_Travail { get; set; }
        public bool Type_E_S { get; set; }
        public System.DateTime Date_E_S { get; set; }
        public bool Assuj_CI { get; set; }
        public string Sit_Fam { get; set; }
        public string Code_User { get; set; }
        public string N_CB { get; set; }
        public string Type_Nbj_Travail { get; set; }
        public Nullable<int> N_Decompte { get; set; }
        public Nullable<int> NB_Jours_Mal { get; set; }
        public Nullable<decimal> Salaire_Mal { get; set; }
        public Nullable<int> Nb_Jours_At { get; set; }
        public Nullable<decimal> Salaire_At { get; set; }
        public Nullable<int> Nb_Jours_Mat { get; set; }
        public Nullable<decimal> Salaire_Mat { get; set; }
        public Nullable<System.DateTime> Date_Recep { get; set; }
        public string Etat { get; set; }
        public string Id_Agence { get; set; }
        public string Sexe { get; set; }
    
        public virtual Annee_CP Annee_CP { get; set; }
        public virtual Salarie Salarie { get; set; }
    }
}
