//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListeSalarier
    {
        public string id_agence { get; set; }
        public int id_CotisantNonAff { get; set; }
        public int N_OrdreCh { get; set; }
        public string N_Cotisant { get; set; }
        public System.DateTime DateVisite { get; set; }
        public string PrenomControleur { get; set; }
        public string NomControleur { get; set; }
        public string Rais_Soc_Fr { get; set; }
        public string Nom { get; set; }
        public Nullable<System.DateTime> Date_Naiss { get; set; }
        public string Lieu_Naiss { get; set; }
        public Nullable<System.DateTime> D_recrut { get; set; }
        public string Obeservation { get; set; }
        public string AdresseCh { get; set; }
    }
}
