//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mise_Jour
    {
        public decimal Numero { get; set; }
        public string N_Cotisant { get; set; }
        public System.DateTime Date_Valable { get; set; }
        public System.DateTime Date_Delivre { get; set; }
        public string Der_Per { get; set; }
        public int Nb_Sal { get; set; }
        public string Observ { get; set; }
        public string Code_User { get; set; }
        public string Rais_Soc_Ar { get; set; }
        public string Rais_Soc_Fr { get; set; }
        public string Type { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Cotisant Cotisant { get; set; }
    }
}
