//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mise_Demeure_Detail
    {
        public string N_Cotisant { get; set; }
        public int N_Piece { get; set; }
        public string C_Periode { get; set; }
        public string C_Nature { get; set; }
        public decimal Montant { get; set; }
        public decimal Montant_Simul { get; set; }
        public string Code_User { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Cotisant Cotisant { get; set; }
        public virtual Mise_Demeure Mise_Demeure { get; set; }
        public virtual Nature Nature { get; set; }
        public virtual Periode Periode { get; set; }
    }
}
