//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mise_Demeure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mise_Demeure()
        {
            this.Mise_Demeure_Detail = new HashSet<Mise_Demeure_Detail>();
        }
    
        public string N_Cotisant { get; set; }
        public int N_Piece { get; set; }
        public System.DateTime D_Etab { get; set; }
        public decimal Mt_Du { get; set; }
        public decimal Mt_Simul { get; set; }
        public string Etat { get; set; }
        public string Observ { get; set; }
        public Nullable<System.DateTime> D_Accus { get; set; }
        public string T_Accus { get; set; }
        public string Code_User { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Cotisant Cotisant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mise_Demeure_Detail> Mise_Demeure_Detail { get; set; }
    }
}
