//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CacobatphEntities : DbContext
    {
        public CacobatphEntities()
            : base("name=CacobatphEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Affiliation> Affiliations { get; set; }
        public virtual DbSet<Agence> Agences { get; set; }
        public virtual DbSet<Agence_Banq> Agence_Banq { get; set; }
        public virtual DbSet<Annee_CP> Annee_CP { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Banque> Banques { get; set; }
        public virtual DbSet<Bomop> Bomops { get; set; }
        public virtual DbSet<Bordereau> Bordereaux { get; set; }
        public virtual DbSet<Bordereau_Rmp> Bordereau_Rmp { get; set; }
        public virtual DbSet<Canal> Canals { get; set; }
        public virtual DbSet<Cert_Bleu> Cert_Bleu { get; set; }
        public virtual DbSet<Cert_Bleu_Temp> Cert_Bleu_Temp { get; set; }
        public virtual DbSet<Chantier_CI> Chantier_CI { get; set; }
        public virtual DbSet<ChantierHistorique> ChantierHistoriques { get; set; }
        public virtual DbSet<Chantier> Chantiers { get; set; }
        public virtual DbSet<ChantiersSupprime> ChantiersSupprimes { get; set; }
        public virtual DbSet<Classe> Classes { get; set; }
        public virtual DbSet<Competence> Competences { get; set; }
        public virtual DbSet<Compte> Comptes { get; set; }
        public virtual DbSet<Conge_Annuel> Conge_Annuel { get; set; }
        public virtual DbSet<constat> constats { get; set; }
        public virtual DbSet<ContacteInfo> ContacteInfoes { get; set; }
        public virtual DbSet<ContacteInfoPiéce> ContacteInfoPiéce { get; set; }
        public virtual DbSet<Contentieu> Contentieux { get; set; }
        public virtual DbSet<Contrainte> Contraintes { get; set; }
        public virtual DbSet<Control> Controls { get; set; }
        public virtual DbSet<Convocation> Convocations { get; set; }
        public virtual DbSet<ConvocationHistorique> ConvocationHistoriques { get; set; }
        public virtual DbSet<ConvocationPiece> ConvocationPieces { get; set; }
        public virtual DbSet<ConvocationPieceHistorique> ConvocationPieceHistoriques { get; set; }
        public virtual DbSet<ConvocationPieceSupprime> ConvocationPieceSupprimes { get; set; }
        public virtual DbSet<ConvocationSupprime> ConvocationSupprimes { get; set; }
        public virtual DbSet<Cot_Classe> Cot_Classe { get; set; }
        public virtual DbSet<Cotisant> Cotisants { get; set; }
        public virtual DbSet<Cotisant_Account> Cotisant_Account { get; set; }
        public virtual DbSet<Cotisant_History> Cotisant_History { get; set; }
        public virtual DbSet<CotisantNonAff> CotisantNonAffs { get; set; }
        public virtual DbSet<DAC_Controle> DAC_Controle { get; set; }
        public virtual DbSet<DA> DAS { get; set; }
        public virtual DbSet<DataFile> DataFiles { get; set; }
        public virtual DbSet<Declarat> Declarats { get; set; }
        public virtual DbSet<Decompte> Decomptes { get; set; }
        public virtual DbSet<Decompte_Archive> Decompte_Archive { get; set; }
        public virtual DbSet<Decompte_CI> Decompte_CI { get; set; }
        public virtual DbSet<Detail_Bord_Rmp> Detail_Bord_Rmp { get; set; }
        public virtual DbSet<Ecrit_Enc> Ecrit_Enc { get; set; }
        public virtual DbSet<Ecrit_Fact> Ecrit_Fact { get; set; }
        public virtual DbSet<Employeur> Employeurs { get; set; }
        public virtual DbSet<Employeur_CI> Employeur_CI { get; set; }
        public virtual DbSet<Encaiss> Encaisses { get; set; }
        public virtual DbSet<EncaissWeb> EncaissWebs { get; set; }
        public virtual DbSet<Ent_Fact> Ent_Fact { get; set; }
        public virtual DbSet<EntetPlanCharge> EntetPlanCharges { get; set; }
        public virtual DbSet<ENTREPRISE> ENTREPRISEs { get; set; }
        public virtual DbSet<ENTREPRISEHistorique> ENTREPRISEHistoriques { get; set; }
        public virtual DbSet<EntrepriseNonAff> EntrepriseNonAffs { get; set; }
        public virtual DbSet<ENTREPRISESupprimee> ENTREPRISESupprimees { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Exploitation> Exploitations { get; set; }
        public virtual DbSet<FicheControleHistorique> FicheControleHistoriques { get; set; }
        public virtual DbSet<FicheControleP> FicheControlePs { get; set; }
        public virtual DbSet<FicheControleSupprime> FicheControleSupprimes { get; set; }
        public virtual DbSet<FicheVisite> FicheVisites { get; set; }
        public virtual DbSet<FicheVisiteHistorique> FicheVisiteHistoriques { get; set; }
        public virtual DbSet<FicheVisiteSupprime> FicheVisiteSupprimes { get; set; }
        public virtual DbSet<Hist_Das> Hist_Das { get; set; }
        public virtual DbSet<HistModifAffilSal> HistModifAffilSals { get; set; }
        public virtual DbSet<Identification> Identifications { get; set; }
        public virtual DbSet<Infraction> Infractions { get; set; }
        public virtual DbSet<Instance_CI> Instance_CI { get; set; }
        public virtual DbSet<Journee> Journees { get; set; }
        public virtual DbSet<Jours_Feries> Jours_Feries { get; set; }
        public virtual DbSet<Ligne_DAS> Ligne_DAS { get; set; }
        public virtual DbSet<Ligne_DAS_Info> Ligne_DAS_Info { get; set; }
        public virtual DbSet<Ligne_DAS_Info_Archive> Ligne_DAS_Info_Archive { get; set; }
        public virtual DbSet<Ligne_DAS_Info_Err_Ok> Ligne_DAS_Info_Err_Ok { get; set; }
        public virtual DbSet<Ligne_DAS_Info_Err_Rejet> Ligne_DAS_Info_Err_Rejet { get; set; }
        public virtual DbSet<Ligne_DAS_Tmp> Ligne_DAS_Tmp { get; set; }
        public virtual DbSet<Ligne_Fact> Ligne_Fact { get; set; }
        public virtual DbSet<ListeSalarier> ListeSalariers { get; set; }
        public virtual DbSet<Main_Levee> Main_Levee { get; set; }
        public virtual DbSet<Mandat> Mandats { get; set; }
        public virtual DbSet<Mise_Demeure> Mise_Demeure { get; set; }
        public virtual DbSet<Mise_Demeure_Detail> Mise_Demeure_Detail { get; set; }
        public virtual DbSet<Mise_Jour> Mise_Jour { get; set; }
        public virtual DbSet<Modif_Salarie> Modif_Salarie { get; set; }
        public virtual DbSet<Mois> Mois { get; set; }
        public virtual DbSet<Motif_Retour> Motif_Retour { get; set; }
        public virtual DbSet<MotifsInfraction> MotifsInfractions { get; set; }
        public virtual DbSet<Nap> Naps { get; set; }
        public virtual DbSet<Nat_Classe> Nat_Classe { get; set; }
        public virtual DbSet<Nationalite> Nationalites { get; set; }
        public virtual DbSet<Nature> Natures { get; set; }
        public virtual DbSet<Nature_Intemperie> Nature_Intemperie { get; set; }
        public virtual DbSet<Nature_Travail> Nature_Travail { get; set; }
        public virtual DbSet<Notif_Contrainte> Notif_Contrainte { get; set; }
        public virtual DbSet<NotificationContrainte> NotificationContraintes { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<Opposition> Oppositions { get; set; }
        public virtual DbSet<Opposition_Detail> Opposition_Detail { get; set; }
        public virtual DbSet<Partiellement> Partiellements { get; set; }
        public virtual DbSet<Periode> Periodes { get; set; }
        public virtual DbSet<PlannifeHistorique> PlannifeHistoriques { get; set; }
        public virtual DbSet<PlannifeSupprime> PlannifeSupprimes { get; set; }
        public virtual DbSet<PlanningPlanifie> PlanningPlanifies { get; set; }
        public virtual DbSet<PlanningPonctuel> PlanningPonctuels { get; set; }
        public virtual DbSet<PonctuelHistorique> PonctuelHistoriques { get; set; }
        public virtual DbSet<PonctuelSupprime> PonctuelSupprimes { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Proc_Penale> Proc_Penale { get; set; }
        public virtual DbSet<PvHistorique> PvHistoriques { get; set; }
        public virtual DbSet<PvInfraction> PvInfractions { get; set; }
        public virtual DbSet<PvInfractionPiece> PvInfractionPieces { get; set; }
        public virtual DbSet<PvinfractionPieceHistorique> PvinfractionPieceHistoriques { get; set; }
        public virtual DbSet<PvinfractionPieceSupprime> PvinfractionPieceSupprimes { get; set; }
        public virtual DbSet<PvInfractionSupprime> PvInfractionSupprimes { get; set; }
        public virtual DbSet<PvRapport> PvRapports { get; set; }
        public virtual DbSet<RapportHistorique> RapportHistoriques { get; set; }
        public virtual DbSet<RapportPieceHistorique> RapportPieceHistoriques { get; set; }
        public virtual DbSet<RapportPieceSupprime> RapportPieceSupprimes { get; set; }
        public virtual DbSet<RapportVisite> RapportVisites { get; set; }
        public virtual DbSet<RapportVisitePieceRA> RapportVisitePieceRAS { get; set; }
        public virtual DbSet<RapportVisiteRa> RapportVisiteRas { get; set; }
        public virtual DbSet<RapportVisitesPiece> RapportVisitesPieces { get; set; }
        public virtual DbSet<RapportVisiteSupprime> RapportVisiteSupprimes { get; set; }
        public virtual DbSet<Rapprochement> Rapprochements { get; set; }
        public virtual DbSet<Reception_CI> Reception_CI { get; set; }
        public virtual DbSet<RecpJourn> RecpJourns { get; set; }
        public virtual DbSet<Reglement_Chq> Reglement_Chq { get; set; }
        public virtual DbSet<Rejet_CI> Rejet_CI { get; set; }
        public virtual DbSet<Routage> Routages { get; set; }
        public virtual DbSet<Salarie> Salaries { get; set; }
        public virtual DbSet<Salarie_Compte> Salarie_Compte { get; set; }
        public virtual DbSet<SalariesHistorique> SalariesHistoriques { get; set; }
        public virtual DbSet<SalariesPieceHistorique> SalariesPieceHistoriques { get; set; }
        public virtual DbSet<SalariesPieceSupprime> SalariesPieceSupprimes { get; set; }
        public virtual DbSet<SalariesSupprime> SalariesSupprimes { get; set; }
        public virtual DbSet<Secteur> Secteurs { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Sessions_Generees> Sessions_Generees { get; set; }
        public virtual DbSet<Statut> Statuts { get; set; }
        public virtual DbSet<TabGeogr> TabGeogrs { get; set; }
        public virtual DbSet<TabPost> TabPosts { get; set; }
        public virtual DbSet<Taux_Cot> Taux_Cot { get; set; }
        public virtual DbSet<Totalement> Totalements { get; set; }
        public virtual DbSet<TypeMotifsInfra> TypeMotifsInfras { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserGroupPrest> UserGroupPrests { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<UtilisateurPrest> UtilisateurPrests { get; set; }
        public virtual DbSet<Ville> Villes { get; set; }
        public virtual DbSet<Wilaya> Wilayas { get; set; }
        public virtual DbSet<HistEncAMJ> HistEncAMJs { get; set; }
        public virtual DbSet<Recap_CI> Recap_CI { get; set; }
        public virtual DbSet<SAConnection> SAConnections { get; set; }
    }
}
