//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modif_Salarie
    {
        public string New_Salarie { get; set; }
        public string Old_Salarie { get; set; }
        public System.DateTime Date_Modif { get; set; }
        public string Id_Agence { get; set; }
    }
}
