//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nature()
        {
            this.Ecrit_Enc = new HashSet<Ecrit_Enc>();
            this.Ecrit_Fact = new HashSet<Ecrit_Fact>();
            this.Ligne_Fact = new HashSet<Ligne_Fact>();
            this.Mise_Demeure_Detail = new HashSet<Mise_Demeure_Detail>();
            this.Nat_Classe = new HashSet<Nat_Classe>();
            this.Taux_Cot = new HashSet<Taux_Cot>();
        }
    
        public string Code { get; set; }
        public string Libelle_Fr { get; set; }
        public string Libelle_Ar { get; set; }
        public string Type { get; set; }
        public string Categorie { get; set; }
        public byte Ordre { get; set; }
        public string C_MR { get; set; }
        public string C_Ctx { get; set; }
        public string N_Compte { get; set; }
        public string C_Op { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Compte Compte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ecrit_Enc> Ecrit_Enc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ecrit_Fact> Ecrit_Fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligne_Fact> Ligne_Fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mise_Demeure_Detail> Mise_Demeure_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nat_Classe> Nat_Classe { get; set; }
        public virtual Operation Operation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Taux_Cot> Taux_Cot { get; set; }
    }
}
