//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationContrainte
    {
        public int Id { get; set; }
        public string Annee { get; set; }
        public string Jour { get; set; }
        public string Mois { get; set; }
        public string NomPrenomControleur { get; set; }
        public string NomSociete { get; set; }
        public string AdresseSocieté { get; set; }
        public string Deposer { get; set; }
        public string Trubunal { get; set; }
        public Nullable<System.DateTime> Date_Marquage { get; set; }
        public Nullable<int> Num_Marquage { get; set; }
        public Nullable<double> Montant { get; set; }
        public string Reference { get; set; }
        public string Id_Agence { get; set; }
        public Nullable<System.DateTime> Modifierle { get; set; }
        public string ModifierPar { get; set; }
        public string Codeuser { get; set; }
        public string Agence { get; set; }
    }
}
