//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opposition_Detail
    {
        public string N_Cotisant { get; set; }
        public int N_Piece { get; set; }
        public string C_Banque { get; set; }
        public string C_Ag_Banque { get; set; }
        public string N_Compte { get; set; }
        public string Etat { get; set; }
        public string Observ { get; set; }
        public string Code_User { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Agence_Banq Agence_Banq { get; set; }
        public virtual Cotisant Cotisant { get; set; }
        public virtual Opposition Opposition { get; set; }
    }
}
