//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanningPonctuel
    {
        public string N_cotisant { get; set; }
        public int Id_CotisantNonAff { get; set; }
        public int N_ordreCh { get; set; }
        public System.DateTime DateVisite { get; set; }
        public string Id_Agence { get; set; }
        public System.DateTime Datedebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public string CodeUser { get; set; }
        public Nullable<System.DateTime> ModifierLe { get; set; }
        public string ModifierPar { get; set; }
    }
}
