//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public string N_Cotisant { get; set; }
        public string C_Position { get; set; }
        public System.DateTime D_Position { get; set; }
        public string Code_User { get; set; }
        public Nullable<System.DateTime> D_Operation { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Cotisant Cotisant { get; set; }
    }
}
