//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proc_Penale
    {
        public string N_Cotisant { get; set; }
        public int N_Piece { get; set; }
        public string Type { get; set; }
        public System.DateTime D_Etablis { get; set; }
        public int N_Encaiss { get; set; }
        public string M_Rejet { get; set; }
        public decimal Mt_Du { get; set; }
        public string Trib { get; set; }
        public string Cours { get; set; }
        public decimal Mt_Ind { get; set; }
        public string Observ { get; set; }
        public string Etat { get; set; }
        public string Code_User { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Cotisant Cotisant { get; set; }
    }
}
