//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PvRapport
    {
        public int Id { get; set; }
        public string Annee { get; set; }
        public string Jour { get; set; }
        public string Heure { get; set; }
        public string Mois { get; set; }
        public string NomPrenomControleur { get; set; }
        public string NomSociete { get; set; }
        public string adresseAgence { get; set; }
        public string Agence { get; set; }
        public string Responsable { get; set; }
        public string AdresseResponsable { get; set; }
        public string Fonction { get; set; }
        public Nullable<System.DateTime> DateRapport { get; set; }
        public string N_Rapport { get; set; }
        public string Destinataire { get; set; }
        public string Id_Agence { get; set; }
        public Nullable<System.DateTime> Modifierle { get; set; }
        public string ModifierPar { get; set; }
        public string NumeroPiece { get; set; }
        public Nullable<System.DateTime> Datelivraison { get; set; }
        public string Codeuser { get; set; }
        public Nullable<bool> Refusrecevoirnotification { get; set; }
        public string NaturePiece { get; set; }
        public string TelephoneAgence { get; set; }
    }
}
