//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rapprochement
    {
        public int N_Ordre { get; set; }
        public string Annee_DAS { get; set; }
        public string Empl_DAS { get; set; }
        public string Salarie_DAS { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public System.DateTime Date_Naiss { get; set; }
        public string Profession { get; set; }
        public string Id_Agence { get; set; }
        public string ETAT { get; set; }
        public string Utilisateur { get; set; }
        public string Num_SS { get; set; }
    }
}
