//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recap_CI
    {
        public int IdBord { get; set; }
        public string N_Employeur { get; set; }
        public string N_Chantier { get; set; }
        public Nullable<System.DateTime> Date_Validation { get; set; }
        public Nullable<System.DateTime> Date_Paiement { get; set; }
        public string Etat { get; set; }
        public string Id_Agence { get; set; }
    }
}
