//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception_CI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reception_CI()
        {
            this.Decompte_CI = new HashSet<Decompte_CI>();
        }
    
        public int Num_Ch { get; set; }
        public string N_Emp_CI { get; set; }
        public string Nom_Emp_CI { get; set; }
        public string Prenom_Emp_CI { get; set; }
        public string Nom_Com { get; set; }
        public string Adresse_Ch { get; set; }
        public System.DateTime Date_Reception { get; set; }
        public System.DateTime Date_Arret { get; set; }
        public Nullable<System.DateTime> Date_Reprise { get; set; }
        public string Type_Declaration { get; set; }
        public string Obs { get; set; }
        public string Code { get; set; }
        public string Etat { get; set; }
        public Nullable<int> NbSalariech { get; set; }
        public string IdRejet { get; set; }
        public string IdInstance { get; set; }
        public Nullable<System.DateTime> Date_Bord { get; set; }
        public Nullable<System.DateTime> Date_Etat_Nom { get; set; }
        public Nullable<int> IdWilaya { get; set; }
        public Nullable<int> IdVille { get; set; }
        public Nullable<int> Annee { get; set; }
        public string IdNature { get; set; }
        public Nullable<int> EffectTotal { get; set; }
        public string Id_Agence { get; set; }
        public Nullable<System.DateTime> Date_Reception_Reprise { get; set; }
        public Nullable<decimal> ChargePatronal { get; set; }
        public Nullable<decimal> ChargeCP { get; set; }
        public Nullable<decimal> ChargeCI { get; set; }
        public Nullable<decimal> Brut { get; set; }
        public string StateSalary { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string RIB { get; set; }
        public string Banque_Libelle { get; set; }
        public string Telephone { get; set; }
        public string UserName { get; set; }
    
        public virtual Chantier_CI Chantier_CI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Decompte_CI> Decompte_CI { get; set; }
        public virtual Instance_CI Instance_CI { get; set; }
        public virtual Nature_Intemperie Nature_Intemperie { get; set; }
        public virtual Rejet_CI Rejet_CI { get; set; }
    }
}
