//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routage
    {
        public string Agence { get; set; }
        public string Adresse_IP { get; set; }
        public string Mot_Passe { get; set; }
        public string Code_Agence { get; set; }
    }
}
