//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salarie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salarie()
        {
            this.Conge_Annuel = new HashSet<Conge_Annuel>();
            this.Decomptes = new HashSet<Decompte>();
            this.Ligne_DAS = new HashSet<Ligne_DAS>();
            this.Mandats = new HashSet<Mandat>();
            this.Salarie_Compte = new HashSet<Salarie_Compte>();
        }
    
        public string Numero { get; set; }
        public string Nom { get; set; }
        public Nullable<System.DateTime> Date_Naiss { get; set; }
        public string Lieu_Naiss { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string C_Postal { get; set; }
        public string Sit_Fam { get; set; }
        public string Profession { get; set; }
        public string Prenom { get; set; }
        public string Assuj_CI { get; set; }
        public string Nom_Latin { get; set; }
        public string Prenom_Latin { get; set; }
        public string Presume { get; set; }
        public string Handicape { get; set; }
        public string Decede { get; set; }
        public string Etranger { get; set; }
        public string Id_Agence { get; set; }
        public string Sexe { get; set; }
        public string N_Cpt { get; set; }
        public string C_Banque { get; set; }
        public string C_Ag_Banq { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string CinNumber { get; set; }
        public string IdNat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conge_Annuel> Conge_Annuel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Decompte> Decomptes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligne_DAS> Ligne_DAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mandat> Mandats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salarie_Compte> Salarie_Compte { get; set; }
    }
}
