//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.Decomptes = new HashSet<Decompte>();
            this.Mandats = new HashSet<Mandat>();
            this.Sessions_Generees = new HashSet<Sessions_Generees>();
        }
    
        public System.DateTime Date_Debut { get; set; }
        public Nullable<System.DateTime> Date_Paiement { get; set; }
        public string Etat { get; set; }
        public string Code_Usager { get; set; }
        public string Imprimee { get; set; }
        public string Annee { get; set; }
        public string Id_Agence { get; set; }
    
        public virtual Annee_CP Annee_CP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Decompte> Decomptes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mandat> Mandats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sessions_Generees> Sessions_Generees { get; set; }
    }
}
