//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions_Generees
    {
        public int Id { get; set; }
        public System.DateTime C_Session { get; set; }
        public System.DateTime Date_Gen { get; set; }
        public decimal Montant { get; set; }
        public int NbTitre { get; set; }
        public string Code_User { get; set; }
        public string Id_Agence { get; set; }
        public string Type { get; set; }
        public int Ref { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
