//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Name { get; set; }
        public Nullable<int> Password { get; set; }
        public string ChangePassword { get; set; }
        public string Manager { get; set; }
        public string Code { get; set; }
        public string Id_Agence { get; set; }
        public string Finance { get; set; }
    }
}
