//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilisateurPrest
    {
        public string Code { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string MotPasse { get; set; }
        public string Groupe { get; set; }
        public string Actif { get; set; }
        public string User_Rec { get; set; }
        public string Id_Agence { get; set; }
        public string Attribut { get; set; }
    
        public virtual UserGroupPrest UserGroupPrest { get; set; }
    }
}
